#!/usr/bin/env python3

import logging
import boto3
from botocore.exceptions import ClientError
from botocore.config import Config
from botocore.session import Session
import urllib

import click

logger = logging.getLogger('minio_presign')
FORMAT = '%(asctime)s  %(message)s'
logging.basicConfig(format=FORMAT)
logger.setLevel(logging.WARNING)



def create_presigned_post(profile_name, bucket_name, object_name,
                          fields=None, conditions=None, expiration=3600):
    """Generate a presigned URL S3 POST request to upload a file (Doesn't work with Minio!)

    :param profile_name: string
    :param bucket_name: string
    :param object_name: string
    :param fields: Dictionary of prefilled form fields
    :param conditions: List of conditions to include in the policy
    :param expiration: Time in seconds for the presigned URL to remain valid
    :return: Dictionary with the following keys:
        url: URL to post to
        fields: Dictionary of form fields and values to submit with the POST
    :return: None if error.
    """

    # Generate a presigned S3 POST URL
    session = boto3.session.Session(profile_name=profile_name)
    my_config = Config(
        signature_version = 's3v4',        
    )    
    s3_client = session.client('s3',  config=my_config, endpoint_url='http://localhost:9000')
    try:
        response = s3_client.generate_presigned_post(bucket_name,
                                                     object_name,
                                                     Fields=fields,
                                                     Conditions=conditions,
                                                     ExpiresIn=expiration)
    except ClientError as e:
        logging.error(e)
        return None

    # The response contains the presigned URL and required fields
    return response

@click.command()
@click.option('--profile', default='myminio', help='Name of profile')
@click.option('--bucket_name', required=True, help='Name of the bucket.')
@click.option('--object_name', required=True, help='Object name in the bucket.')
@click.option('-v', '--verbose', count=True)

def presigned_put(profile, bucket_name, object_name, verbose):
    if verbose > 0:
        logger.setLevel(logging.DEBUG)
        boto3.set_stream_logger('', logging.DEBUG)

    # retrieve the endpoint for this profile
    session = Session()
    config = session.full_config 
    assert 'endpoint' in config[profile], f"{profile} should contain an `endpoint`"
    endpoint_url = config[profile]['endpoint']

    session = boto3.session.Session(profile_name=profile)
    my_config = Config(
        signature_version = 's3v4',        
    )    
    s3_client = session.client('s3',  config=my_config, endpoint_url=endpoint_url)

    url = s3_client.generate_presigned_url(
        ClientMethod = 'put_object',
        Params = {
            'Bucket': bucket_name,
            'Key': object_name,
        }
    )
    print(url)




if __name__ == '__main__':
    presigned_put()
